### ISSUE TITLE
Confusion of using duration flag

### ISSUE THREAD

**Issue by ypwu1** [go-pluto/styx#1]
I try to export cpu usage of container service. the query is `sum(rate(container_cpu_usage_seconds_total{name="some-container-id"}[1m])) by (name) * 100`  inside the query, I already specify the duration which is 1 minute. How does Duration flag relate to my query? For example, If I want last 6hours data with time interval is 1min? what does the query look like?

**Comment by metalmatze** [comment]
If you want to export the last 6 hours the intervals are being computed just like Prometheus does compute the intervals. So you don't need to care about those.
