### ISSUE TITLE
Upgrade CLI to v2 and added arbitrary ranges

### ISSUE THREAD

**Issue by mfranzil** [go-pluto/styx#15]
Hi,

I made a few modifications to your project, as I needed to be able to retrieve an arbitrary range in time from Prometheus without just telling a duration.

I took the opportunity of upgrading the cli package to v2, and cleaned up some code. I plan on making some more modifications, but you may find the code here.

https://github.com/mfranzil/styx

I can open a PR if you're interested.

**Comment by metalmatze** [comment]
Hey!

That's really cool! Definitely post a PR and we can discuss which pieces etc to take into the project. If they aren't too crazy it should be fine.

**Comment by mfranzil** [comment]
Done! See #16. Probably some more edits are needed (or we can cherry-pick some modifications), but let me know what you think about it!
