### ISSUE TITLE
Install Issues

### ISSUE THREAD

**Issue by celsocesila** [go-pluto/styx#3]
Hi,

I'm having problems to install Styx properly. When I try to run the installation command present the following message:

xxxx@yyyyyy ~ $ go get -v -u github.com/go-pluto/styx
github.com/go-pluto/styx (download)
github.com/go-pluto/styx
# github.com/go-pluto/styx
GO/src/github.com/go-pluto/styx/prometheus.go:115: undefined: sort.Slice
GO/src/github.com/go-pluto/styx/writer.go:28: undefined: sort.Slice
GO/src/github.com/go-pluto/styx/writer.go:76: undefined: sort.Slice

Any idea what can I do?

**Comment by metalmatze** [comment]
Hey!
Yes, you need a newer version of Go. The `sort.Slice` function was introduced within the last year. Try at least Go 1.8+.

**Comment by metalmatze** [comment]
If this doesn't resolve the issue please feel free to reopen this issue. I'm closing for now.
