### ISSUE TITLE
styx don‘t work

### ISSUE THREAD

**Issue by donydex** [go-pluto/styx#4]
I run this command 
```
styx -d 2m 'go_goroutines'
```

![image](https://user-images.githubusercontent.com/11333398/48672766-1de44400-eb75-11e8-9943-476ad682a087.png)

My promethus works right. I can get the data by wget.
![image](https://user-images.githubusercontent.com/11333398/48672777-453b1100-eb75-11e8-9fea-87e7ec3160e9.png)

and it dont work just stop there and dont give any response.

This is the htop result:

![image](https://user-images.githubusercontent.com/11333398/48672723-78c96b80-eb74-11e8-9427-c750265e4f48.png)

**Comment by metalmatze** [comment]
It works for me like that when I port-forward Prometheus to  `localhost:9090`. You might need to adjust the `--prometheus` flag to point to something else than `http://localhost:9090`.

**Comment by donydex** [comment]
Thanks！It works！
